# Generated by Django 3.2.3 on 2021-06-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
                ('class_durr_in_hours', models.IntegerField(default=2)),
                ('class_day', models.CharField(max_length=20)),
                ('lab_durr_in_hours', models.IntegerField(default=2)),
                ('lab_day', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.CharField(max_length=20)),
                ('class_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='api.user')),
                ('class_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_date', models.DateField(auto_now_add=True)),
                ('class_type', models.CharField(max_length=50)),
                ('week_held', models.IntegerField()),
                ('start', models.TimeField(auto_now_add=True)),
                ('end', models.TimeField(blank=True)),
                ('participants', models.IntegerField(default=1)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordClass', to='api.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=50)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myUser', to='api.user')),
            ],
        ),
    ]
