# Generated by Django 3.2.3 on 2021-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='added_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='start',
            field=models.TimeField(blank=True),
        ),
    ]
