# Generated by Django 3.2.3 on 2021-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210617_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
    ]
