# Generated by Django 3.2.3 on 2021-06-18 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_records_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='class_name',
        ),
        migrations.AddField(
            model_name='homework',
            name='accepted',
            field=models.CharField(default='waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
