# Generated by Django 3.2.3 on 2021-06-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210618_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Tasks',
        ),
    ]
