# Generated by Django 3.2.3 on 2021-06-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_homework_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(blank=True)),
                ('accepted', models.CharField(default='waiting', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
